services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    networks:
      - app-network
    depends_on:
      - db
  db:
    image: postgres:17.2-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastcartdb
    ports:
      - "5432:5432"
    volumes:
      - fastcart-api-postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  pgadmin:
    image: dpage/pgadmin4:8.14.0
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    volumes:
      - fastcart-api-pgadmin_data:/var/lib/pgadmin
    networks:
      - app-network

volumes:
  fastcart-api-postgres_data:
  fastcart-api-pgadmin_data:

networks:
  app-network:
    driver: bridge