services:
  test-db:
    image: postgres:17.2-alpine
    container_name: test_postgres_db
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d test_db"]
      interval: 5s
      retries: 5
